// next imports
import Head from 'next/head';

// react imports 
import { useState, useRef } from 'react';

// component imports
import Message from '../components/Message';
import VehicleInfoList from '../components/VehicleInfoList';

// css imports
import styles from '../styles/Home.module.css'
import VinForm from '../components/VinForm';

const Home = ({ VIN_API }) => {
  // state
  const [carInfo, setCarInfo] = useState({});

  const [vinText, setVinText] = useState('');

  const [error, setError] = useState(false);

  const [hasSearched, setHasSearched] = useState(false);

  const [formatError, setFormatError] = useState(false);

  const [showResults, setShowResults] = useState(false);

  const [isLoading, setIsLoading] = useState(false);

  const vinInputElementRef = useRef();

  const changeInput = (e) => setVinText(e.target.value);

  const fetcher = async (nextAPIURL) => {
    const response = await fetch(nextAPIURL, {
      headers: {
        "vin": vinText,
      }
    });

    const { hasError, carInfo } = await response.json();

    if (hasError) {
      setError(true);
    } else {
      setError(false);
    }

    return carInfo;
  }

  const findCarInfo = async () => {
    if (vinText.length !== 17) return setFormatError(true);

    setIsLoading(true);

    setFormatError(false);

    const carInfo = await fetcher(VIN_API);

    setHasSearched(true);

    setIsLoading(false);

    setCarInfo(carInfo);

    !error && setShowResults(true);
  };

  const resetAllConditions = () => {
    setCarInfo(null);

    setVinText('');

    setError(false);

    setHasSearched(false);

    setFormatError(false);

    setIsLoading(false);

    vinInputElementRef.current.value = '';
  }
  return (
    <main className={styles.main}>
      <Head>
        <title>VIN Finder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Message hasSearched={hasSearched} error={error} carInfo={carInfo} />
      <h1 className={styles.h1}>Find Vehicle Information by VIN Number</h1>
      <VinForm vinInputElementRef={vinInputElementRef} formatError={formatError} findCarInfo={findCarInfo} isLoading={isLoading} vinText={vinText} onChangeInput={changeInput} />
      <VehicleInfoList showResults={showResults} carInfo={carInfo} />
      <button onClick={resetAllConditions} >Reset All</button>
      <p>Vin Finder© created by Brian Ruff</p>
    </main >
  )
}

export function getStaticProps() {
  return {
    props: {
      VIN_API: process.env.VIN_API,
      TEST_VIN_API: process.env.TEST_VIN_API,
    }
  }
}


export default Home;
